// try {
//   functionerrfound();
// } catch (error) {
//   console.error(error);
// }

// try {
//   tyrStatement;
// } catch (exceptionVar) {
//   catcheStatement;
// } finally {
//   finallyStatement;
// }

// try {
//   throw "Oops; this is not an Error object";
// } catch (e) {
//   if (!(e instanceof Error)) {
//     e = new Error(e);
//   }
//   console.error(e.message);
// }

try {
  console.log("hello ");
  console.log(error);
  console.log("error is Occuring "); // excepttion of the this error go to the next line
} catch {
  console.log("handeling");
  console.log("the end console of catch ");
}
console.log("end");
